[[executable]]
name = "shell"
deps = ["core", "log", "ipc", "ustd"]
ld_flags = "-Wl,-dynamic-linker,/bin/dynamic-linker"
sources = [
    "ast.cc",
    "lexer.cc",
    "line_editor.cc",
    "main.cc",
    "parser.cc",
    "token.cc",
]
