[[command]]
command = "$build_root/tools/mkfont $root/FantasqueSansMono.ttf $build_root/kernel/font.cc 24"
deps = ["mkfont"]
output = "font.cc"

[[executable]]
name = "kernel"
deps = [
    "ustd-no-sse",
]

cxx_flags = "-ffreestanding -mno-red-zone -mno-sse"
ld_flags = "-T$root/kernel/arch/amd64/linker.ld -no-pie"
sources = [
    "acpi/apic_table.cc",
    "acpi/pci_table.cc",
    "acpi/root_table.cc",
    "acpi/table.cc",
    "arch/amd64/cpu.S",
    "arch/amd64/cpu.cc",
    "arch/amd64/interrupt.S",
    "arch/amd64/smp.S",
    "arch/amd64/syscall.S",
    "arch/amd64/syscall.cc",
    "dev/dev_fs.cc",
    "dev/device.cc",
    "dev/dmesg_device.cc",
    "dev/framebuffer_device.cc",
    "fs/file_handle.cc",
    "fs/inode.cc",
    "fs/inode_file.cc",
    "fs/ram_fs.cc",
    "fs/vfs.cc",
    "intr/interrupt_manager.cc",
    "intr/io_apic.cc",
    "ipc/double_buffer.cc",
    "ipc/pipe.cc",
    "ipc/server_socket.cc",
    "ipc/socket.cc",
    "mem/heap.cc",
    "mem/memory_manager.cc",
    "mem/physical_page.cc",
    "mem/region.cc",
    "mem/virt_space.cc",
    "pci/enumerate.cc",
    "pci/function.cc",
    "proc/process.cc",
    "proc/scheduler.cc",
    "proc/thread.cc",
    "proc/thread_blocker.cc",
    "time/hpet.cc",
    "time/time_manager.cc",
    "console.cc",
    "dmesg.cc",
    "font.cc",
    "kmain.cc",
    "syscalls.cc",
    "ub_san.cc",
]

[option.kernel_qemu_debug]
cxx_flags = "-DKERNEL_QEMU_DEBUG"

[option.kernel_stack_protector]
cxx_flags = "-fstack-protector-strong -mstack-protector-guard=global"

[option.kernel_ubsan]
cxx_flags = "-fsanitize=address -fno-sanitize=function"
