[[command]]
command = "$build_root/tools/mkfont $root/FantasqueSansMono.ttf $build_root/servers/console/font.cc 24"
deps = ["mkfont"]
output = "font.cc"

[[executable]]
name = "console-server"
deps = ["config", "core", "log", "ipc", "ustd"]
sources = [
    "escape_parser.cc",
    "font.cc",
    "framebuffer.cc",
    "main.cc",
    "terminal.cc",
]
