sources = [
    "builtin.cc",
    "string.cc",
    "string_builder.cc",
    "string_view.cc",
]

[[library]]
name = "ustd"

[[library]]
name = "ustd-no-sse"
cxx_flags = "-mno-sse"

[[library]]
name = "ustd-uefi"
cxx_flags = """\
-fshort-wchar \
-mno-red-zone \
-mno-sse \
-target x86_64-unknown-windows \
"""
