[[executable]]
name = "usb-server"
deps = ["config", "core", "log", "ipc", "ustd"]
sources = [
    "device.cc",
    "endpoint.cc",
    "host_controller.cc",
    "keyboard_device.cc",
    "main.cc",
    "port.cc",
    "trb_ring.cc",
]
