name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ghcr.io/yeetari/umbongo:master
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: >-
          python3 configure.py
          -Bbuild
          -p release
          -e assertions
      - name: Build
        run: ninja -C build
