name: Build
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Install tools
        run: >-
          apt install -y
          clang
          cmake
          libfreetype-dev
          lld
          nasm
          ninja-build
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure CMake
        run: >-
          cmake .
          -Bbuild
          -DBUILD_TYPE=Release
          -DBUILD_WARNINGS=ON
          -DENABLE_ASSERTIONS=ON
          -DKERNEL_UBSAN=ON
          -DLINK_TIME_OPT=ON
          -GNinja
      - name: Build
        run: cmake --build build
