name: Code Style
on: [push, pull_request]
jobs:
  clang-format:
    name: Clang Format
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Install tools
        run: >-
          apt install -y
          clang-format
          git
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run clang-format
        shell: bash
        run: |
          git config --global --add safe.directory $(pwd)
          find . -name '*.cc' -or -name '*.hh' | xargs clang-format -i
          git diff | tee format-diff
          if [ -s format-diff ]; then exit 1; fi

  include-what-you-use:
    name: Include What You Use
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Install tools
        run: >-
          apt install -y
          clang
          cmake
          git
          iwyu
          libfreetype-dev
          lld
          nasm
          ninja-build
          parallel
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure CMake
        run: |
          cmake . -Bbuild
      - name: Run include-what-you-use
        run: |
          find . \
            -name '*.cc' \
            -and -not -name 'mkfont.cc' \
            -print0 |
          parallel -0 \
            include-what-you-use \
              -std=c++20 \
              -ffreestanding \
              -nostdinc \
              -nostdinc++ \
              -I. \
              -Ibuild \
              -Ilibs \
              -Ilibs/posix \
              -w \
              {} 2>&1 |
          grep -v correct | sed -e :a -e '/^\n*$/{$d;N;};/\n$/ba' | cat -s | tee output
          if [ -s output ]; then exit 1; fi
