name: Static Analysis
on: [push, pull_request]
jobs:
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    container: ubuntu:22.04
    env:
      DEBIAN_FRONTEND: noninteractive
    steps:
      - name: Update package lists
        run: apt update -qq
      - name: Install tools
        run: >-
          apt install -y
          clang
          cmake
          clang-tidy
          lld
          nasm
          parallel
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure CMake
        run: cmake . -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          find . \
            -name '*.cc' \
            -and -not -name 'mkfont.cc' \
            -print0 |
          parallel -0 \
            clang-tidy -p build --header-filter=.* --quiet {} 2>/dev/null |
          tee output
          if [ -s output ]; then exit 1; fi
