name: Static Analysis
on: [push, pull_request]
jobs:
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    container: ubuntu:devel
    steps:
      - name: Install tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update -qq
          apt install -y \
            clang \
            cmake \
            clang-tidy \
            libstdc++-11-dev \
            lld \
            nasm \
            parallel
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure CMake
        run: |
          cmake . -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run clang-tidy
        run: |
          find . \
            -name '*.cc' \
            -and -not -name 'FontGenerator.cc' \
            -print0 |
          parallel -0 \
            clang-tidy -p build --header-filter=.* --quiet {} |
          tee output
          if [ -s output ]; then exit 1; fi

  cppcheck:
    name: Cppcheck
    runs-on: ubuntu-latest
    container: ubuntu:devel
    steps:
      - name: Install tools
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update -qq
          apt install -y \
            clang \
            cmake \
            cppcheck \
            libstdc++-11-dev \
            lld \
            nasm
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure CMake
        run: |
          cmake . -Bbuild -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
      - name: Run cppcheck
        run: |
          cppcheck \
            --project=build/compile_commands.json \
            --suppress=*:*freetype\* \
            --suppress=*:*Vector.hh \
            --quiet \
            2>&1 | tee output
          if [ -s output ]; then exit 1; fi
