name: Static Analysis
on: [push, pull_request]
jobs:
  clang-tidy:
    name: Clang Tidy
    runs-on: ubuntu-latest
    container: ghcr.io/yeetari/umbongo:master
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure
        run: python3 configure.py -Bbuild
      - name: Run clang-tidy
        run: |
          ninja -C build -t compdb > build/compile_commands.json
          find . \
            -name '*.cc' \
            -and -not -name 'mkfont.cc' \
            -print0 |
          parallel -0 \
            clang-tidy -p build --header-filter=.* --quiet {} 2>/dev/null |
          tee output
          if [ -s output ]; then exit 1; fi
